config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: 'sign_in'
    get 'sign_up', to: 'devise/registrations#new', as: 'sign_up'
    get 'sign_out', to: 'devise/sessions#destroy', as: 'sign_out'
  end

  root to: 'articles#index'
  resources :articles do
    resources :comments, only: %i[create update destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, :post, presence: true
  validates :title, length: { maximum: 100 }
  validates :post, length: { maximum: 10_000 }
  validates_associated :user

  scope :posted, -> { where(post: '5') }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  belongs_to :parent, class_name: 'Comment', optional: true

  validates :body, presence: true, length: { maximum: 10_000 }
  validates_associated :user, :article

  def comments
    Comment.where(parent_id: id)
  end

  def destroy
    if comments.present?
      update(user_id: nil, body: nil)
    else
      super
    end
  end

  def destroy?
    if user.nil?
      true
    else
      super
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_validation :set_name

  has_many :articles
  has_many :comments

  validates :name, presence: true, length: { maximum: 16 }

  def set_name
    self.name = "unit #{rand(999)}" if name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :error, :notice, :alert

  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  helper_method :current_user_can_edit?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:user) do |user_params|
      user_params.permit(:email, :password, :remember_me)
    end
  end

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  def current_user_can_edit?(event)
    user_signed_in? && current_user == event.user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]

  before_action :set_article, only: %i[show]
  before_action :set_current_user_article, only: %i[edit update destroy]

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article, success: 'Post has created!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, success: 'Post has updated!'
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @article.nil?
      redirect_to root_path
    else
      @article.destroy

      redirect_to articles_path, success: 'Post has deleted!'
    end
  end

  private

  def set_current_user_article
    @article ||= current_user.articles.find_by(id: params[:id])
  end

  def set_article
    @article ||= Article.find_by(id: params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]

  before_action :set_article
  before_action :set_current_user_article, only: %i[edit update destroy]

  def create
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user
    # render json: { error: @comment.errors }, status: 403
    if @comment.parent_id.nil?
      if @comment.save
        render partial: 'comments/entry-point', locals: { comment: @comment }
      else
        render json: { error: 'Can\'t create an empty comment' }, status: 403
      end
    else
      if @comment.save
        render partial: 'comments/parent-list', locals: { comment: @comment }
      else
        render json: { error: 'Can\'t create an empty comment' }, status: 403
      end
    end
  end

  def update; end

  def destroy
    if @comment.nil?
      render json: { error: 'You are trying to delete not your comment.
                             Go away you little scumbag!' }, status: 403
    else
      @comment.destroy
    end
  end

  private

  def set_article
    @article = Article.find_by(id: params[:article_id])
  end

  def set_current_user_article
    @comment ||= current_user.comments.find_by(id: params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :article_id, :parent_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show; end

  private

  def set_user
    @user ||= User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(type)
    list = {
      success: "alert-massage-success",
      error: "alert-massage-danger",
      alert: "alert-massage-warning",
      notice: "alert-massage-info"
    }

    list[type.to_sym]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articles.html.erb
<% articles.each do |article| %>
  <div class="mb-4" id="accordion" role="tablist">
    <div class="hek">
      <div class="d-table d-flex justify-content-center">
        <button type="button" class="btn btn-secondary shadow">▲</button>
      </div>
      <div class="d-table my-2 w-100 tif">
        <div class="tex">12764</div>
      </div>
      <div class="d-table d-flex justify-content-center">
        <button type="button" class="btn btn-secondary shadow">▼</button>
      </div>
      <div class="card mt-3 mx-4" data-toggle="collapse" href="#collapse<%= "#{article.id}" %>" aria-expanded="true" aria-controls="collapse<%= "#{article.id}" %>">
        <div class="px-3 font-weight-bold text-center">−</div>
      </div>
    </div>
    <div class="d-flex flex-row">
      <div class="w-100">
        <div class="card shadow">
          <div class="card-header">
            <strong class="card-title" style="font-size: 25px"><%= link_to "#{article.title}", article_path(article.id) %></strong>
          </div>
          <div id="collapse<%= "#{article.id}" %>" class="collapse show" role="tabpanel" aria-labelledby="heading<%= "#{article.id}" %>">
            <div class="card-body">
              <p class="card-text"><%= simple_format(article.post) %></p>
            </div>
          </div>
          <div class="card-footer text-right">
            <div class="float-left">Creator: <%= link_to "#{article.user.name}", user_path(article.user) %></div>
            <div class="float-right"><%= distance_of_time_in_words(Time.now, article.created_at, include_seconds: true) %></div>
            <div class="clearfix"></div>
            <div>1</div>
            <div>1</div>
            <div>1</div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div>
  <%= form_with(model: @article, local: true) do |f| %>

    <% if @article.errors.any? %>
      <div class="alert alert-danger pt-4">
        <h2 class="text-center">
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul style="padding-left: 100px">
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <form>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label"><%= f.label :title %></label>
        <div class="col-sm-10">
          <%= f.text_field :title, class: 'form-control', placeholder: '' %>
        </div>
      </div>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label"><%= f.label :post %></label>
        <div class="col-sm-10">
          <%= f.text_area :post, class: 'form-control', rows: 10 %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
          <%= f.submit 'Save', class: 'btn btn-success' %>
        </div>
      </div>
    </form>

  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<div class="form-group row">
  <div class="col-sm-10 offset-sm-2">
    <%= link_to 'Back', articles_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/articles/index.html.erb
<%= render partial: "articles/articles", locals: { articles: @articles } %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<div class="form-group row">
  <div class="col-sm-10 offset-sm-2">
    <%= link_to 'Back', articles_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/articles/show.html.erb
<%= render 'articles/articles', articles: [@article] %>

<% if current_user_can_edit? @article %>
  <div class="d-flex justify-content-around mt-4">
    <%= link_to 'Back', articles_path, class: 'btn btn-success shadow px-5' %>
    <%= link_to 'Edit', edit_article_path, class: 'btn btn-success shadow px-5' %>
    <%= link_to 'Delete', article_path, method: :delete,
                data: { confirm: 'Are you sure?' }, class: 'btn btn-success shadow px-5' %>
  </div>
<% end %>

<div class="card mt-4 shadow">
  <div class="card-header">
    <h1 class="mt-1">Comments:</h1>
  </div>
  <div class="card-body">
    <% if @article.comments.count == 0 %>
      <div class="no-comments">This article has no comments yet</div>
    <% else %>
      <% @article.comments.each do |comment| %>
        <% if comment.parent_id == nil %>
          <%= render 'comments/entry-point', comment: comment %>
        <% end %>
      <% end %>
    <% end %>
    <div class="dnone" id="insert-parent"></div>
  </div>
  <div class="card-footer">
    <%= render 'comments/form', id: 'new-parent-comment' %>
  </div>
</div>

app/views/comments/_body.html.erb
<% if comment.body.nil? %>
  <div class="comment">
    <div class="comment-head">
        <div class="user-name">
          [DELETED]
        </div>
      <div class="comment-time">
        <%= distance_of_time_in_words(Time.now, comment.created_at, include_seconds: true) %> ago
      </div>
      <div class="comment-reference">
        <div class="">
          <i class="fab fa-bootstrap"></i>
        </div>
        <div class="">
          <i class="fab fa-bootstrap"></i>
        </div>
        <div class="">
          <i class="fab fa-bootstrap"></i>
        </div>
      </div>
    </div>
    <div class="comment-btn" >
      <a id="reply-btn">replay</a>
    </div>
    <div class="dnone" id="reply-form"><%= render 'comments/form', parent_id: comment.id, id: 'new-child-comment', close: 'close-form' %></div>
  </div>
<% else %>
  <div class="comment">
    <div class="comment-head">
      <div class="comment-rate">
        <div class="rate">+35</div>
        <div class="vote-up">▲</div>
        <div class="vote-down">▼</div>
      </div>
      <div class="comment-owner">
        <div class="user-avatar"><i class="far fa-dizzy"></i></div>
        <div class="user-name">
          <%= comment.user.name %>
        </div>
      </div>
      <div class="comment-time">
        <%= distance_of_time_in_words(Time.now, comment.created_at, include_seconds: true) %> ago
      </div>
      <div class="comment-reference">
        <div class="">
          <i class="fab fa-bootstrap"></i>
        </div>
        <div class="">
          <i class="fab fa-bootstrap"></i>
        </div>
        <div class="">
          <i class="fab fa-bootstrap"></i>
        </div>
      </div>
    </div>
    <div class="comment-body">
      <%= comment.body %>
    </div>
    <div class="comment-btn" >
      <a id="reply-btn">replay</a>
      <%= link_to 'delete', [@article, comment], method: :delete, remote: true,
                  data: { confirm: 'Are you sure?' }, class: "#{local_assigns[:del_sign]}" if current_user_can_edit? comment %>
    </div>
    <div class="dnone" id="reply-form"><%= render 'comments/form', parent_id: comment.id, id: 'new-child-comment', close: 'close-form' %></div>
  </div>
<% end %>

app/views/comments/_entry-point.html.erb
<div class="comment-main">
  <%= render 'comments/body', comment: comment%>
  <% if comment.comments.present? %>
    <% comment.comments.each do |comment| %>
      <%= render 'comments/system', comment: comment%>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@article, Comment.new], class: "mt-2 #{local_assigns[:id]}", remote: true, data: {type: :json } do |f| %>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', placeholder: 'type text of a commentary', id: "#{rand}" %>
  </div>
  <div class="form">
    <% if local_assigns.has_key? :parent_id %>
      <%= f.hidden_field :parent_id, value: local_assigns[:parent_id], id: "#{rand}" %>
    <% end %>
    <%= f.submit 'Save', class: "btn btn-success #{local_assigns[:close]}", style: 'width: 133px;' %>
  </div>
<% end %>

app/views/comments/_parent-comment.html.erb
<div class="parent-comment">
  <%= render 'comments/body', comment: comment, del_sign: 'delete-child-btn' %>
  <% if comment.comments.present? %>
    <%= render 'comments/parent-list', comment: comment%>
  <% end %>
  <div></div>
</div>

app/views/comments/_parent-list.html.erb
<div class="parent-list">
  <div class="toggle"><i class="far fa-caret-square-up"></i></div>
  <div class="toggle dnone"><i class="far fa-caret-square-down"></i></div>
  <div class="hidden-link dnone">Раскрыть ветку&nbsp;&nbsp;<i class="far fa-comment-alt"></i></div>
  <% if comment.comments.present? %>
    <% comment.comments.each do |comment| %>
      <%= render 'comments/parent-comment', comment: comment%>
    <% end %>
  <% else %>
    <%= render 'comments/parent-comment', comment: comment%>
  <% end %>
</div>

app/views/comments/_system.html.erb
<div class="parent-list">
  <div class="toggle"><i class="far fa-caret-square-up"></i></div>
  <div class="toggle dnone"><i class="far fa-caret-square-down"></i></div>
  <div class="hidden-link dnone">Раскрыть ветку&nbsp;&nbsp;<i class="far fa-comment-alt"></i></div>
  <div class="parent-comment">
    <%= render 'comments/body', comment: comment%>
    <% if comment.comments.present? %>
      <% comment.comments.each do |comment| %>
        <%= render 'comments/system', comment: comment%>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div id="ajax-notice-insert"></div>
    <%= render 'shared/notices' %>

    <section class="container content q">
      <div class="row">
        <div class="col-9">
          <%= yield %>
        </div>
        <div class="col-3">
          <%= render 'shared/rightbar' %>
        </div>
      </div>
    </section>

    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>

    <%= render 'shared/notices' %>

    <div class="container">
      <div class="row">
        <div class="col-3"></div>
        <div class="col-6 mt-5">
          <div class="card shadow">
            <div class="card-body">
              <%= yield %>
            </div>
          </div>
        </div>
        <div class="col-3"></div>
      </div>
    </div>

    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer-body">
  <div class="container">

  </div>
</div>

app/views/shared/_head.html.erb
<title>Gizeh</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light nav-bar-priority shadow">
  <div class="container">
    <%= link_to 'Gizeh', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "#{bootstrap_class_for(type)} info" %>
  <% end %>
<% end %>

app/views/shared/_rightbar.html.erb
<div class="card">
  <div class="card-body shadow">
    <% if user_signed_in? %>
      <h4 class="card-title"><%= link_to "#{current_user.name}", user_path(current_user.id) %></h4>
      <h6 class="card-subtitle mb-2 text-muted"><%= current_user.email %></h6>
      <div class="card-text">
        <ul class="ul">
          <li><%= link_to 'Articles', user_path(current_user.id) %></li>
          <li><%= link_to 'Comments', '#' %></li>
          <li><%= link_to 'Saved', '#' %></li>
          <li><%= link_to 'Subscribes', '#' %></li>
          <li><%= link_to 'Ban-list', '#' %></li>
          <li><%= link_to 'Notes', '#' %></li>
        </ul>
      </div>
      <%= link_to 'Sign out', sign_out_path , class: 'text-left mt-2 d-block'  %>
    <% else %>
      <h4 class="card-title text-center">Authorization</h4>
      <form class="form-group my-2">
        <%= link_to 'Sign in', sign_in_path, class: 'btn btn-success d-block' %>
      </form>
      <%= link_to 'Sign up', sign_up_path, class: 'text-center d-block' %>
    <% end %>
  </div>
</div>
<%= link_to '+ New Post', new_article_path, class: 'btn btn-success mt-4 d-block shadow' %>
<div class="card mt-4 shadow">
  <div class="card-header">
    Comment of the day
  </div>
  <div class="card-body">
    <h4 class="card-title">Username</h4>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
  </div>
</div>

app/views/users/show.html.erb
<div class="card shadow">
  <div class="card-title image rounded-top" id="set">

  </div>
  <div class="card-body" style="background-col p-2 text-centeror: white">
    <h1 class="text-center mt-2"><%= @user.name %></h1>
    <p class="text-center">On Gizeh 2 days</p>
    <div class="d-flex justify-content-center mb-5"><%= link_to 'Edit profile', '#' %></div>
    <hr>
    <p class="text-center">Pushed 0 pluses and 0 minuses</p>
    <hr>
    <div class="d-flex">
      <div class="col p-2 text-center font-weight-bold">100</div>
      <div class="col p-2 text-center font-weight-bold">0</div>
      <div class="col p-2 text-center font-weight-bold">0</div>
      <div class="col p-2 text-center font-weight-bold"><%= @user.articles.count %></div>
      <div class="col p-2 text-center font-weight-bold">0</div>
    </div>
    <div class="d-flex ">
      <div class="col p-2 text-center text-center">Rating</div>
      <div class="col p-2 text-center">Subs</div>
      <div class="col p-2 text-center">Comments</div>
      <div class="col p-2 text-center">Articles</div>
      <div class="col p-2 text-center">In hot</div>
    </div>
  </div>
</div>
<div class="card shadow my-4">
  <div class="card-body">
    <div class="d-flex">
      <div class="col p-2 text-center">On time</div>
      <div class="col p-2 text-center">On rating</div>
      <div class="col p-2 text-center">[MINE]</div>
      <div class="col p-2 text-center">Search</div>
      <div class="col p-2 text-center">Icon</div>
    </div>
  </div>
</div>

<% if @user.articles.count == 0 %>
  <div class="card shadow mt-4">
    <div class="card-body">
      There are no posts here yet
    </div>
  </div>
<% else %>
  <%= render partial: "articles/articles", locals: { articles: @user.articles } %>
<% end %>